app:
    resource: '@AppBundle/Controller/'
    type: annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

groups:
    type:     rest
    resource: AppBundle\Controller\GroupController

users:
    type:     rest
    resource: AppBundle\Controller\UserController
